### ISSUE TITLE
9.10 and 8.51 do not work anymore.

### ISSUE THREAD

**Issue by algebrique** [0xZylox/FortniteGame-Base-Modding-Project#5]
Today I downloaded the new version of the 9.10 and 8.51 projects, and when I tried to cook for Windows, it did not work. I tried to just open the file, not change anything, and cook the project, and it said, "Cooked Failed." Can you help me ?

**Comment by zyloxmods** [comment]
Can you upload the log so I can check for erros thanks

**Comment by algebrique** [comment]
[Log.txt](https://github.com/zyloxmods/FNGameProj/files/15167275/Log.txt)

**Comment by zyloxmods** [comment]
Let me know if either 1b49b62c5b0639a861624901b8092712014928a5 (8.51) or 1b49b62c5b0639a861624901b8092712014928a5  (9.10) fixed the issue

**Comment by algebrique** [comment]
[Log.txt](https://github.com/zyloxmods/FNGameProj/files/15167554/Log.txt)
dont work for the 8.51 project

**Comment by RRlevrai** [comment]
me too its dont work can you tell me send me the Fortnite base moding uproject pls

**Comment by zyloxmods** [comment]
> me too its dont work can you tell me send me the Fortnite base moding uproject pls

you are on the repo rn

**Comment by zyloxmods** [comment]
im working on fixing it

**Comment by arm00n** [comment]
fortnite.

**Comment by RRlevrai** [comment]
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.AbilityEffect.Ninja.ThrowingStars.AdditionalStars. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.AbilityEffect.Ninja.ThrowingStars.AdditionalStars, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.Gameplay.Mod.CritMultiplier.Weapon.Ranged. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.Gameplay.Mod.CritMultiplier.Weapon.Ranged, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.Gameplay.Mod.ImpactMultiplier. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.Gameplay.Mod.ImpactMultiplier, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.Perk.Hipshot.T02. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.Perk.Hipshot.T02, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.PerkEffect.CorrosiveStars.Affliction. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.PerkEffect.CorrosiveStars.Affliction, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Asset.PerkEffect.Outlander.AntiMaterialCharge.PawnDamage. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Asset.PerkEffect.Outlander.AntiMaterialCharge.PawnDamage, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag GameplayCue.Perk.Outlander.AntiMaterialCharge.PawnDamage. from source DefaultGameplayTags.ini: Tag ends with .! Still dont wana cook after the update 
Replacing with GameplayCue.Perk.Outlander.AntiMaterialCharge.PawnDamage, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Granted.AlterationEffect.OnMeleeHitStackBuffCritRate.Active. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Granted.AlterationEffect.OnMeleeHitStackBuffCritRate.Active, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Granted.AlterationEffect.OnMeleeHitStackBuffFireRate.Active. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Granted.AlterationEffect.OnMeleeHitStackBuffFireRate.Active, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Granted.AlterationEffect.OnMeleeHitStackBuffMoveSpeed.Active. from source DefaultGameplayTags.ini: Tag ends with .! Replacing with Granted.AlterationEffect.OnMeleeHitStackBuffMoveSpeed.Active, you may need to modify InvalidTagCharacters
UATHelper: Cooking (Windows):   LogInit: Display: LogGameplayTags: Error: Invalid tag Granted.AlterationEffect.OnRangedFireStackBuffDa

**Comment by RRlevrai** [comment]
still dont cook after the update

**Comment by zyloxmods** [comment]
it does

**Comment by algebrique** [comment]
work for me

**Comment by algebrique** [comment]
thank u Zylox

**Comment by zyloxmods** [comment]
both cooking erros should have been fixed with 806e9e5ca9ddfee8bb2956051a3e121811630c1d and 5020e207ea26571499c7725294a6fba3a540b3cd
